### ISSUE TITLE
Key Error when running Redfold 

### ISSUE THREAD

**Issue by IseultLeahy** [aky3100/REDfold#1]
I have tried to train Redfold and run it on some fasta files. Both times I received a key error. 

redfold <dir_of_fasta_files>
`Traceback (most recent call last):
  File "/home/ec2-user/.local/bin/redfold", line 8, in <module>
    sys.exit(main())
  File "/home/ec2-user/.local/lib/python3.7/site-packages/redfold/__main__.py", line 15, in main
    process_data(args, file1,file2)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/redfold/process_data.py", line 129, in process_data
    one_hot_mat2= one_hot_2m(seq.upper())
  File "/home/ec2-user/.local/lib/python3.7/site-packages/redfold/process_data.py", line 40, in one_hot_2m
    feat[L1-1,dcBASE2[Id1]]= 1
KeyError: 'AT'`

redfold -train <dir_of_bpseq_files>
`Traceback (most recent call last):
  File "/home/ec2-user/.local/bin/redfold", line 8, in <module>
    sys.exit(main())
  File "/home/ec2-user/.local/lib/python3.7/site-packages/redfold/__main__.py", line 15, in main
    process_data(args, file1,file2)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/redfold/process_data.py", line 129, in process_data
    one_hot_mat2= one_hot_2m(seq.upper())
  File "/home/ec2-user/.local/lib/python3.7/site-packages/redfold/process_data.py", line 40, in one_hot_2m
    feat[L1-1,dcBASE2[Id1]]= 1
KeyError: 'AK'`

Is there a way to resolve this?

**Comment by Anjana-mp** [comment]
Hi, Did you resolve the issue? I am also getting the same

**Comment by Anjana-mp** [comment]
> I have tried to train Redfold and run it on some fasta files. Both times I received a key error.
> 
> redfold <dir_of_fasta_files> `Traceback (most recent call last): File "/home/ec2-user/.local/bin/redfold", line 8, in <module> sys.exit(main()) File "/home/ec2-user/.local/lib/python3.7/site-packages/redfold/__main__.py", line 15, in main process_data(args, file1,file2) File "/home/ec2-user/.local/lib/python3.7/site-packages/redfold/process_data.py", line 129, in process_data one_hot_mat2= one_hot_2m(seq.upper()) File "/home/ec2-user/.local/lib/python3.7/site-packages/redfold/process_data.py", line 40, in one_hot_2m feat[L1-1,dcBASE2[Id1]]= 1 KeyError: 'AT'`
> 
> redfold -train <dir_of_bpseq_files> `Traceback (most recent call last): File "/home/ec2-user/.local/bin/redfold", line 8, in <module> sys.exit(main()) File "/home/ec2-user/.local/lib/python3.7/site-packages/redfold/__main__.py", line 15, in main process_data(args, file1,file2) File "/home/ec2-user/.local/lib/python3.7/site-packages/redfold/process_data.py", line 129, in process_data one_hot_mat2= one_hot_2m(seq.upper()) File "/home/ec2-user/.local/lib/python3.7/site-packages/redfold/process_data.py", line 40, in one_hot_2m feat[L1-1,dcBASE2[Id1]]= 1 KeyError: 'AK'`
> 
> Is there a way to resolve this?

Did you resolve the issue? I am also getting the same

**Comment by Anjana-mp** [comment]
> I have tried to train Redfold and run it on some fasta files. Both times I received a key error.
> 
> redfold <dir_of_fasta_files> `Traceback (most recent call last): File "/home/ec2-user/.local/bin/redfold", line 8, in <module> sys.exit(main()) File "/home/ec2-user/.local/lib/python3.7/site-packages/redfold/__main__.py", line 15, in main process_data(args, file1,file2) File "/home/ec2-user/.local/lib/python3.7/site-packages/redfold/process_data.py", line 129, in process_data one_hot_mat2= one_hot_2m(seq.upper()) File "/home/ec2-user/.local/lib/python3.7/site-packages/redfold/process_data.py", line 40, in one_hot_2m feat[L1-1,dcBASE2[Id1]]= 1 KeyError: 'AT'`
> 
> redfold -train <dir_of_bpseq_files> `Traceback (most recent call last): File "/home/ec2-user/.local/bin/redfold", line 8, in <module> sys.exit(main()) File "/home/ec2-user/.local/lib/python3.7/site-packages/redfold/__main__.py", line 15, in main process_data(args, file1,file2) File "/home/ec2-user/.local/lib/python3.7/site-packages/redfold/process_data.py", line 129, in process_data one_hot_mat2= one_hot_2m(seq.upper()) File "/home/ec2-user/.local/lib/python3.7/site-packages/redfold/process_data.py", line 40, in one_hot_2m feat[L1-1,dcBASE2[Id1]]= 1 KeyError: 'AK'`
> 
> Is there a way to resolve this?

Did you resolved the issue? I am getting the same error
